prologin2015_arg/prologin2015_arg/urls.py
from django.conf.urls import include, url
from django.contrib import admin

urlpatterns = [
    # Examples:
    # url(r'^$', 'prologin2015_arg.views.home', name='home'),
    # url(r'^blog/', include('blog.urls')),

    url(r'^admin/', include(admin.site.urls)),
    url(r'^quizz/', include('quizz.urls')),
]

prologin2015_arg/quizz/urls.py
from django.conf.urls import url
from . import views

urlpatterns = [
    url(r'^$', views.index, name='index'),
    url(r'^hack$', views.hack, name='hack'),
    url(r'^capture/(?P<faction_id>[0-9]+)$', views.capture, name='capture'),
]

prologin2015_arg/quizz/models.py
from django.db import models
from django.utils import timezone
import time

# Create your models here.

class Question(models.Model):
    question_text = models.CharField(max_length=200)
    image = models.CharField(max_length=200, blank=True)
    current_question = models.BooleanField(default=False)
    already_asked = models.BooleanField(default=False)
    times_asked = models.IntegerField(default=0)
    def __str__(self):
        return self.question_text

class Answer(models.Model):
    question = models.ForeignKey(Question)
    answer_text = models.CharField(max_length=200)
    good_answer = models.BooleanField(default=False)
    def __str__(self):
        return self.answer_text

class Faction(models.Model):
    faction_name = models.CharField(max_length=200)
    color = models.CharField(max_length=9)
    icon = models.CharField(max_length=200, blank=True)
    def __str__(self):
        return self.faction_name

class PortalController(models.Model):
    faction = models.ForeignKey(Faction, blank=True)
    control_start = models.DateTimeField(blank=True)
    control_end = models.DateTimeField(blank=True, null=True)
    def __str__(self):
        return self.faction.faction_name
    def capture_time(self):
        if self.control_end is not None:
            capture_duration = self.control_end - self.control_start
            return int(capture_duration.total_seconds() / 60)
        else:
            return "Current capture"

prologin2015_arg/quizz/views.py
from django.shortcuts import render, redirect
from .models import Question, Answer, Faction, PortalController
import time
#from django.db.models import Max
from django.utils import timezone
from datetime import datetime
import random

# Create your views here.

def get_current_faction():
    last_controller = PortalController.objects.all().order_by('control_start').reverse()
    if len(last_controller) > 0:
        faction = Faction.objects.get(id=last_controller.faction.id)
    else:
        faction = Faction("Shapers", "#CACACA")
    return faction

def index(request):
    # if the portal has been hacked less than 5 minutes before, lock it
    now = timezone.now()
    captures = PortalController.objects.all().order_by('control_start').reverse()
    # If the portal was already captured (ie not at the beggining of the game)
    if len(captures) > 0:
        last_capture = captures[0]
        if (now - last_capture.control_start).total_seconds() / 60 <= 5:
            faction_color = last_capture.faction.color
            context = {'faction_color': faction_color}
            return render(request, 'quizz/locked.html', context)
        elif (now - last_capture.control_start).total_seconds() / 60 >= 15:
            last_capture.control_end = now
            last_capture.save()
    question_list = Question.objects.filter(current_question=True)
    if len(question_list) > 1:
        question = random.choice(question_list)
    else:
        question = question_list[0]
    faction_color = "#CACACA"
    if len(captures) > 0:
        last_capture = captures[0]
        if last_capture.control_end is None:
            faction_color = last_capture.faction.color
        else:
            faction_color = "#CACACA"
    context = {'question': question, 'faction_color': faction_color}
    return render(request, 'quizz/index.html', context)

def hack(request):
    question = Question.objects.get(id=request.POST['question_id'])
    if 'answer' not in request.POST:
        return redirect('index')
    answer = Answer.objects.get(id=request.POST['answer'])
    if answer.question.id == question.id and answer.good_answer:
        factions = Faction.objects.all()
        context = {'success': True, 'factions': factions}
    else:
        context = {'success': False}
    if context['success']:
        # Get only never asked questions
        question.already_asked = True
        question.current_question = False
        question.times_asked += 1
        question.save()
        available_questions = Question.objects.filter(already_asked=False)
        # If all questions have been asked before
        if len(available_questions) == 0:
            all_questions = Question.objects.all()
            for unit_question in all_questions:
                unit_question.already_asked = False
                unit_question.save()
            available_questions = all_questions
        next_question = random.choice(available_questions)
        next_question.current_question = True
        next_question.save()
    return render(request, 'quizz/hack.html', context)

def capture(request, faction_id):
    now = timezone.now()
    faction = Faction.objects.get(id=faction_id)
    captures = PortalController.objects.all().order_by('control_start').reverse()
    # If the portal was already captured (ie not at the beggining of the game)
    if len(captures) > 0:
        last_capture = captures[0]
        if (now - last_capture.control_start).total_seconds() / 60 >= 5:
            last_capture.control_end = now
            last_capture.save()
        else:
            return render(request, 'quizz/locked.html')
    new_capture = PortalController(faction=faction, control_start=now)
    new_capture.save()
    return render(request, 'quizz/capture.html')

prologin2015_arg/quizz/templates/quizz/capture.html
<meta http-equiv="refresh" content="3; url=http://localhost:8000/quizz" />
Capture in progress…

prologin2015_arg/quizz/templates/quizz/hack.html
<html>
<head>
<title>Prologin 2015</title>
{% if success != True %}
<meta http-equiv="refresh" content="3; url=http://localhost:8000/quizz" />
{% endif %}
</head>
<body style="background:#CACACA">
{% if success == True %}
Hacking successful, congratulations.<br>
For which faction do you wish to claim the portal?<br>
<table>
  <tr>
{% for faction in factions %}
<td>
  <table>
    <tr><td>{{ faction.faction_name }}</td></tr>
    <tr><td><a href="{% url 'capture' faction.id %}">image</a></td></tr>
</table></td>
{% endfor %}
{% else %}
Hacking failed. Lockdown active.
{% endif %}
</body>
</html>

prologin2015_arg/quizz/templates/quizz/index.html
<html>
<head>
<title>Prologin 2015</title>

</head>
<body style="background:{{ faction_color }}">
<h1>{{ question.question_text }}</h1>
<form method="POST" action="{% url 'hack' %}">
{% csrf_token %}
{% for answer in question.answer_set.all %}
<input type="radio" name="answer" value="{{ answer.id }}">{{ answer.answer_text }}<br>
{% endfor %}
<br>
<h2>CAUTION<br>
If the answer is incorrect, the portal will lock itself for 5 minutes</h2>
<input type="hidden" name="question_id" value="{{ question.id }}">
<input type="submit" value="Hack">
</form>
</body>
</html>

prologin2015_arg/quizz/templates/quizz/locked.html
<html>
<head>
<title>Prologin 2015</title>
<meta http-equiv="refresh" content="3; url=http://localhost:8000/quizz" />
</head>
<body style="background:{{ faction_color }}">
<h1>PORTAL LOCKED</h1>
Nice try, hacker.
</body>
</html>